version: '3'

services:
  db:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: drf_homework
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - db
      - app
    healthcheck:
      test: [ "CMD-SHELL", "celery_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_beat:
    build: .
    restart: always
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - db
      - app
    healthcheck:
      test: [ "CMD-SHELL", "celery_beat_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
